[ClassVersion("1.0.0"), FriendlyName("SpecialAccountLanguage")]
class DSC_SpecialAccountLanguage : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies whether to copy the current user settings to the default account. The default account settings will use for new users.")] Boolean CopyToDefaultAccount;
    [Write, Description("Specifies whether to copy the current user settings to the system account. The system account settings will use for the welcome screen.")] Boolean CopyToSystemAccount;
    [Write, Description("Specifies whether to reboot after copy the special accounts settings.")] Boolean RebootAfterCopy;
    [Read, Description("The current user account's culture.")] String CurrentAccountCulture;
    [Read, Description("The current user account's geo location ID.")] String CurrentAccountGeoId;
    [Read, Description("The value from 'HKEY_USERS\\.DEFAULT\\Control Panel\\International\\LocaleName'.")] String DefaultAccountLocaleName;
    [Read, Description("The value from 'HKEY_USERS\\.DEFAULT\\Control Panel\\International\\Geo\\Nation'.")] String DefaultAccountNation;
    [Read, Description("The value from 'HKEY_USERS\\S-1-5-18\\Control Panel\\International\\LocaleName'.")] String SystemAccountLocaleName;
    [Read, Description("The value from 'HKEY_USERS\\S-1-5-18\\Control Panel\\International\\Geo\\Nation'.")] String SystemAccountNation;
};
