#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - squid
runcmd:
  - sed -e '/^#http_access allow localnet$/s/^#//' -i /etc/squid/conf.d/debian.conf
  - echo '[squid] Uncommented http_access allow localnet'
  - systemctl restart squid
  - echo '[squid] Restart'
